version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 281102
      MYSQL_DATABASE: bookingsystem
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  springboot:
    build: .
    container_name: movie_booking_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookingsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 281102
    ports:
      - "8092:8092"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
